x-common-env: &common-env
  AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
  _PIP_ADDITIONAL_REQUIREMENTS: gtfs-realtime-bindings psycopg2-binary requests dbt-core==1.8.2 dbt-postgres==1.8.2 redis==4.6.0

services:
  postgres:
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    restart: unless-stopped

  airflow-scheduler:
    environment:
      <<: *common-env
    volumes:
      - ./dbt:/opt/airflow/dbt
    restart: unless-stopped

  airflow-webserver:
    environment:
      <<: *common-env
    volumes:
      - ./dbt:/opt/airflow/dbt
    restart: unless-stopped

  airflow-worker:
    environment:
      <<: *common-env
    volumes:
      - ./dbt:/opt/airflow/dbt
    restart: unless-stopped

  airflow-triggerer:
    environment:
      <<: *common-env
    volumes:
      - ./dbt:/opt/airflow/dbt
    restart: unless-stopped